#!/bin/sh
# Prepare cpu0 for benchmarks.
set -e
echo 1 > "/sys/devices/system/cpu/intel_pstate/no_turbo"
echo performance > "/sys/devices/system/cpu/cpu0/cpufreq/scaling_governor"
cat "/sys/devices/system/cpu/cpu0/topology/thread_siblings_list" | tr , '\n' | while read n
do
    if [ "$n" -ne 0 ]
    then
        echo 0 > "/sys/devices/system/cpu/cpu$n/online"
    fi
done
