// Code generated by "stringer -type=DependenciesUpdateResultEnum"; DO NOT EDIT.

package main

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[DependenciesUpdateDependencyMissing-0]
	_ = x[DependenciesUpdateContentUpToDate-1]
	_ = x[DependenciesUpdateUpdateScheduled-2]
}

const _DependenciesUpdateResultEnum_name = "DependenciesUpdateDependencyMissingDependenciesUpdateContentUpToDateDependenciesUpdateUpdateScheduled"

var _DependenciesUpdateResultEnum_index = [...]uint8{0, 35, 68, 101}

func (i DependenciesUpdateResultEnum) String() string {
	if i < 0 || i >= DependenciesUpdateResultEnum(len(_DependenciesUpdateResultEnum_index)-1) {
		return "DependenciesUpdateResultEnum(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _DependenciesUpdateResultEnum_name[_DependenciesUpdateResultEnum_index[i]:_DependenciesUpdateResultEnum_index[i+1]]
}
