#!/bin/sh
# Prepare cpu0 for ordinary tasks.
set -e
echo 0 > "/sys/devices/system/cpu/intel_pstate/no_turbo"
echo schedutil > "/sys/devices/system/cpu/cpu0/cpufreq/scaling_governor"
for f in $(grep -lx 0 /sys/devices/system/cpu/cpu*/online)
do
    echo 1 > "$f"
done
